### ISSUE TITLE
Number of active wallets SNOs

### ISSUE THREAD

**Issue by kaloyan-raev** [storj/stats#14]
We provide information about active storage nodes, and it would be even better if we could also have info about the number of operators who run them.

One good approximation is to count the distinct wallets attached to the active nodes:
```
select count(distinct wallet) from nodes where disqualified is null and suspended is null and piece_count > 0;
```

**Comment by NiaStorj** [comment]
linked to - https://github.com/storj/datascience/issues/141

**Comment by grafael** [comment]
@kaloyan-raev I did create this metric on Metabase: https://metabase.datasci.storj.io/question/424-active-wallets-by-satellite

Criteria: Online nodes with `piece_count > 0`

**Comment by stoweandi** [comment]
@grafael I'm seeing a query failed message.

**Comment by grafael** [comment]
@stoweandi fixed.

**Comment by NiaStorj** [comment]
@kaloyan-raev can you mark this ticket as closed. I don't have the access to do so.

**Comment by kaloyan-raev** [comment]
@grafael I see the metrics in Metabase, but it seems they are not available on stats.storjshare.io yet.

**Comment by grafael** [comment]
@kaloyan-raev please check again, just updated the endpoint: https://stats.storjshare.io/nodes.json
Also, there is a PR to update the documentation: https://github.com/storj/stats/pull/16

**Comment by kaloyan-raev** [comment]
Thank you!
