### ISSUE TITLE
Make storage_remote_segments_lost a counter not a rate

### ISSUE THREAD

**Issue by kevinkk525** [storj/stats#6]
according to forum posts from storjlings the metric storage_remote_segments_lost is a rate per hour. This is in my opinion an irrelevant metric unless you expect satellites to loses multiple pieces per hour. But as storj's goal is to never lose a piece, it makes a lot more sense to make this metric a lifetime counter of all lost pieces. this is also good for transparency as it won't be possible to hide lost pieces (as they would move quickly out of the timeframe with a rate/hour)

**Comment by grafael** [comment]
I'm already working on this, we should have a fix soon.

**Comment by grafael** [comment]
Fixed in December 2022
