### ISSUE TITLE
Expose high level location information about nodes

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/stats#7]
Similar to the Storj DCS link-sharing service I want obfuscated location data about the nodes on the network exposed on the public stats site so that I can use that data to generate maps with all of the nodes on the network. 

Here is an example of a map I would like to be able to generate with data from the stats site: 

![Screen Shot 2021-07-27 at 2 36 28 PM](https://user-images.githubusercontent.com/5313116/127209243-f21f4956-beed-40de-9c34-e33e16631b59.png)

**Comment by grafael** [comment]
So, by high level should we focus on Country, State, or City? Also, we need to discuss the data format. 

Suggestion:
Add `geo_location` on http://stats.storj.id/nodes.json 

If we have 420 nodes in Salt lake city and 1337 in New York City, we'll have the following entry :

```json
"geo_location": [
    {
        "latitude": 40.758701,
        "longitude": -111.876183,
        "total_nodes": 420
    },
    {
          "latitude": 40.730610,
          "longitude":  -73.935242,
          "total_nodes": 1337
      }
]
```

**Comment by grafael** [comment]
Due to the number of geolocation records, a new endpoint was created: http://stats.storj.id/nodes_geo.json
Also, the payload is something like (no city aggregation):

```json
{
    "121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6@ap1.storj.io:7777": {
        "locations": [
            {
                "lat": 53.6532,
                "lon": 10.0453
            },
            {
                "lat": 55.9606,
                "lon": 38.0456
            }]
}
```

**Comment by grafael** [comment]
Feature implemented: https://stats.storjshare.io/nodes_geo.json
